export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const SIGNUP_USER = 'SIGNUP_USER';

export const FETCHING_STORES = 'FETCHING_STORES';
export const FETCHED_STORES = 'FETCHED_STORES';

export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS';
